version: '3'

volumes:
  mongo-volume:
    driver: local
  formio-volume:
    driver: local
  bonita-volume:
    driver: local

services:

  mongodb:
    image: mongo
    volumes:
      - mongo-volume:/data/db

  formio-api:
    image: skarvelis/formio-api:1.0
    ports:
      - 3001:3001
    environment:
      - VIRTUAL_HOST={--formio_host--}
      - REVERSE_PROXY=false
      - DB_HOST=mongodb
      - DB_NAME=formio
      - ADMIN_EMAIL={--formio_admin_email--}
      - ADMIN_PASS={--formio_admin_password--}
    depends_on:
      - mongodb
    volumes:
      - formio-volume:/app

  bonita-desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - 6080:80
      - 5900:5900
      - 10000:8080
    environment: 
      - VNC_PASSWORD={--bd_vnc_password--}
      - USER={--bd_user--} 
      - PASSWORD={--bd_password--}
    volumes:
      - bonita-volume:/home/{--bd_user--}

  node:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./obif/:/home/node/app
    ports:
      - 10631:10631
    command: "npm start"


